enigma:
  key-specification:
    key: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    iv: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    padding: PKCS7Padding
    blockCipherMode: CBC
    size: 256

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/enigma
  liquibase:
    change-log: classpath:/db/changelog-local.xml

server:
  ssl:
    key-alias: enigmaserver
    key-store-password: 2secure4u
    key-store-type: pkcs12
    key-store: classpath:enigmaserver.p12
    trust-store-password: 2secure4u
    trust-store-type: pkcs12
    trust-store: classpath:enigmaserver.p12
    client-auth: need

keycloak:
  auth-server-url: https://localhost:12443/auth
  realm: enigma
  resource: enigma-engine
  ssl-required: external
  bearer-only: true
  truststore: classpath:enigmaserver.p12
  truststore-password: 2secure4u