key-management-bo:
  http-port: 10080
enigma:
  client:
    enigma-base-url: "https://localhost:11443/enigma/"
    # key store
    key-store: classpath:enigmaclient.p12
    key-store-password: 2secure4u
    key-store-type: pkcs12
    key-store-alias: enigmaclient
    # trust store
    trust-store: classpath:enigmaclient.p12
    trust-store-password: 2secure4u
    trust-store-type: pkcs12
    oauth2:
      client-id: enigma-admin
      oauth2-token-uri: "https://localhost:12443/auth/realms/enigma/protocol/openid-connect/token"
      client-secret: "2secure4u"
      trust-store: classpath:enigmaclient.p12
      trust-store-password: 2secure4u
      trust-store-type: pkcs12

server:
  ssl:
    key-store-type: pkcs12
    key-store-password: 2secure4u
    key-alias: enigmabackoffice
    key-store: classpath:enigmabackoffice.p12

keycloak:
  auth-server-url: https://localhost:12443/auth
  realm: enigma
  resource: enigma-engine
  ssl-required: all
  bearer-only: true
  truststore: classpath:enigmabackoffice.p12
  truststore-password: 2secure4u
